[remote.github]
owner = "浣犵殑GitHub鐢ㄦ埛鍚?
repo = "MaaKOF_Fate"
# 鑷敤鏃舵崲鎴愯嚜宸辩殑浠撳簱owner鍜宺epo
# 娉ㄦ剰锛屾湰鍦癵it user闇€涓巊ithub涓€鑷存墠鑳藉疄鐜版垚鍔烜
[changelog]
# 鏍囬
header = """
# 鏇存柊鏃ュ織
"""

body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | split(pat="\n") | first | upper_first }} \
        {% if commit.github.username %} @{{ commit.github.username }}{% else %} {{ commit.author.name }}{% endif %}
        {%- if commit.footers -%}
            {%- for footer in commit.footers -%}
                {%- if footer.token == "Co-authored-by" -%}
                    {%- set co_author_name = footer.value | split(pat=" <") | first | trim %} @{{ co_author_name }}
                {%- endif -%}
            {%- endfor -%}
        {%- endif -%}
{% endmacro -%}

{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} ({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}\
    ## 鏈彂甯?{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {%- endfor -%}
{% endfor -%}
{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## 鏂拌础鐚€?鉂わ笍
{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{%- endif %}
"""

# 灏鹃儴
footer = """
"""

[git]
# 杩囨护鎻愪氦
conventional_commits = true # 浣跨敤绾﹀畾寮忔彁浜ゆ牸寮?filter_unconventional = false # 涓嶈繃婊ら潪绾﹀畾寮忔彁浜?# 鍚敤瀹屾暣鐨?commit 淇℃伅
split_commits = false
# 淇濈暀瀹屾暣鐨?commit body
protect_breaking_commits = false
commit_parsers = [
    # 璺宠繃鍖呭惈 [skip changelog] 鐨?commit
    { message = ".*\\[skip changelog\\].*", skip = true },
    { body = ".*\\[skip changelog\\].*", skip = true },
    { message = "^feat", group = "<!-- 0 -->鉁?鏂板姛鑳? },
    { message = "^fix", group = "<!-- 1 -->馃悰 Bug淇" },
    { message = "^docs", group = "<!-- 4 -->馃摎 鏂囨。" },
    { message = "^perf", group = "<!-- 3 -->馃殌 鎬ц兘浼樺寲" },
    { message = "^refactor", group = "<!-- 2 -->馃殰 浠ｇ爜閲嶆瀯" },
    { message = "^style", group = "<!-- 5 -->馃帹 鏍峰紡" },
    { message = "^test", group = "<!-- 6 -->馃И 娴嬭瘯" },
    { message = "^chore\\(deps\\)", group = "馃摝 渚濊禆鏇存柊" },
    { message = "^chore", group = "<!-- 8 -->馃敡 鏃ュ父缁存姢" },
    { message = "^ci", group = "<!-- 7 -->鈿欙笍 鎸佺画闆嗘垚" },
    { body = ".*security", group = "<!-- 9 -->馃敀 瀹夊叏" },
    { message = "^revert", group = "<!-- 10 -->鈼€锔?鎾ら攢" },
]

# 蹇界暐杩欎簺鎻愪氦
ignore_tags = "rc"

# 鎺掑簭瑙勫垯
sort_commits = "oldest"

# 鍚敤GitHub闆嗘垚
[git.github]
commits = true
